import  Footer  from '../app/components/footer/Footer';
import Navbar from '../app/components/navbar/Navbar.jsx'
import './globals.css'
import { ThemeProvider } from '../statemanagment/Theme'
import { Inter } from 'next/font/google'
import AuthProvide from '../app/components/auth/AuthProvide';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Automob',
  description: 'Generated by create next app',
}
//if we add sssio provider here it wont work since client only but then metadata wont work hence improt
export default function RootLayout({  children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
     <AuthProvide>

          <div className="container">
              <Navbar />
              {children}
              <Footer />
            </div>
        
         
            
     </AuthProvide>
        </ThemeProvider>
      </body>
    </html>
  );
}
